272JABSProject/Controllers/FitnessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _272JABSProject.Models;
using _272JABSProject.ViewModels;

namespace _272JABSProject.Controllers
{
    public class FitnessController : Controller
    {

        private FitnessEntities db = new FitnessEntities();

        // GET: Fitness
        public ActionResult Index()
        {
            return View();
        }

        //<<<<<<< HEAD
        //<<<<<<< HEAD
        //<<<<<<< HEAD
        public ActionResult UserProfile()
        {
            return View();
        }
        //<<<<<<< HEAD
        //=======

        public ActionResult FoodAnalysis()
        {
            return View();
        }
        //>>>>>>> Jackie'sBranch
        //=======
        public ActionResult ActivityInput()
        {
            return View();
        }

        public ActionResult FoodInput()
        {
            return View();
        }
        //>>>>>>> brendensbranch
        //=======

        public ActionResult ActivityAnalysis()
        {
            return View();
        }
        //>>>>>>> ShanahsBranch
        //=======
        [HttpGet]
        public ActionResult LogInPage()
        {

            return View();
        }

        [HttpPost]
        public ActionResult LogInPage(string Password , string Email)
        {



            return View();
        }

        [HttpGet]
        public ActionResult SignUpPage()
        {

            ViewBag.UserTypeID = new SelectList(db.UserTypes, "UserTypeID", "UserTypeName");
            ViewBag.GenderID = new SelectList(db.Genders, "GenderID", "GenderName");

            SignUpViewModel SignUp = new SignUpViewModel();
            //SignUp.GenderCollection = db.Genders.ToList<Gender>();

            return View(SignUp);
        }
        //>>>>>>> Amo'sBranch
        [HttpPost]
        public ActionResult SignUpPage([Bind(Include = "UserID,UserName,UserSurname,GenderID,DateOfBirth,Nationality,Email,Password,UserTypeID,XCoordinate,YCoordinate,CurrentWeight,GoalWeight,Height")] User NewUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(NewUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            
            return View();
        }
    }
}

272JABSProject/Views/Fitness/ActivityAnalysis.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Styles.css" rel="stylesheet" />
    <title>ActivityAnalysis</title>
</head>
<body>
    <div id="MainDiv"> 

        <h1>Mindful Body Fitness</h1> <button style="margin-left:1150px" onclick="location.href='@Url.Action("Index", "Fitness")';return false;">Home</button>
        <h2>Activity Analysis</h2>

        <div id="Container">

            <div id="Content">

                <div id="Activities">

                    <div class="ActivityList">
                        <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                        <p>Runing</p>
                        <p>1h 30m</p>
                    </div>

                    <div class="ActivityList">
                        <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                        <p>Runing</p>
                        <p>1h 30m</p>
                    </div>

                    <div class="ActivityList">
                        <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                        <p>Runing</p>
                        <p>1h 30m</p>
                    </div>


                </div> @*end of activities div*@



                <div id="ActivityInfo">

                    <p style="display : inline; background-color: #2196F3; width : 100%;">User's Name</p>
                    <p style="display : inline; margin-left : 30px; background-color: #2196F3; width : 100%;">User's Surname</p>

                    <p>In this section overall information about the user's activities will appear</p>

                </div> @*Acitibity Info DIV*@

            </div> @*Content Div*@

        </div> @*Container Div*@        

    </div> @*main div*@
</body>
</html>

272JABSProject/Views/Fitness/ActivityInput.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ActivityInput</title>
    <link href="~/Content/brendencss.css" rel="stylesheet" />
</head>
<body>
    <h1 style="text-align:center">Mindfull Body Fitness</h1>
    <h2 style="text-align:center">Activity Input</h2>

    <div class="bcontainer">
        <p>
            Activity Type: <select id="activitytype" name="activitytype" onchange="changeReason()">
                <option value="" selected disabled hidden>Select Type</option>
                <option value="Endurance">Endurance</option>
                <option value="Strength">Strength</option>
                <option value="Balance">Balance</option>
                <option value="Flexibility">Flexibility</option>
            </select>
        </p>

        <p>
            Activity: <select id="activity" name="activity">
                <option value="" selected disabled hidden>Select Item</option>
            </select>
        </p>

        <p>Recommended Time/Amount: <input type="text" name="recTAmount"></p>

        <p>Actual Time/Amount: <input type="text" name="actTAmount"></p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "Fitness")';return false;">Save and Submit</button>
            <button onclick="location.href='@Url.Action("Index", "Fitness")';return false;">Go Home</button>
        </p>

    </div>






    <script>
        function changeReason()
        {
            var selectedStatus = document.getElementById("activitytype");
            var Reason = document.getElementById("activity");
            var enduranceArray = new Array("Running", "Swimming", "Biking", "Stair Climbing");
            var strengthArray = new Array("Lifting Weights", "Push-Ups", "Pull-Ups", "Leg-Squats");
            var balanceArray = new Array("Stand on one foot", "Walk heel to toe", "Balance Board", "Shift Weight");
            var flexibilityArray = new Array("Shoulder rolls", "Forward Lunges", "Seat Stretch", "Cross-Over");
            removeOptions(Reason);

            if (selectedStatus.value == "Endurance")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = enduranceArray[i];
                    option.value = enduranceArray[i];
                    Reason.add(option);
                }
            }
            else if (selectedStatus.value == "Strength")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = strengthArray[i];
                    option.value = strengthArray[i];
                    Reason.add(option);
                }
            }
            else if (selectedStatus.value == "Balance")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = balanceArray[i];
                    option.value = balanceArray[i];
                    Reason.add(option);
                }
            }
            else if (selectedStatus.value == "Flexibility")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = flexibilityArray[i];
                    option.value = flexibilityArray[i];
                    Reason.add(option);
                }
            }
        }

        function removeOptions(selectbox)
        {
            for (var x = selectbox.options.length - 1; x >= 0; x--)
            {
                selectbox.remove(x);
            }
        }
    </script>
</body>
</html>

272JABSProject/Views/Fitness/FoodAnalysis.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FoodAnalysis</title>
    <style>
        body {
        }
        .grid-container {
            display: grid;
            grid-template-columns: 60% 37%;
            grid-gap : 40px;
            background-color: #2196F3;
            padding: 10px;
            
        }

        .grid-grid-container{
            display : grid;
            grid-template-columns : 25% 25% 25% 25%;
        }

        .grid-item {
            background-color: rgba(255, 255, 255, 0.8);
            border: 1px solid rgba(0, 0, 0, 0.8);
            padding: 20px;
            padding-top: 0;
            text-align: center;

        }

        .box1 {
            /*align-self:start;*/
            grid-column: 1/3;
            grid-row: 1/3;
        }

        .box2 {
            /*align-self:end;*/
            grid-column: 3;
            grid-row: 1/3;
        }

        #HomePage-Food-Analysis
        {
            grid-template-rows : 1fr 1fr 1fr;
        }

        /*img {
            max-width: 100%;
            height: auto;
            display : block;
        }*/

        .HomePage-Food-Section
        {
            display : grid;
            grid-template-columns : 1fr 1fr 1fr;
        }

        .HomePage-Food-Section p
        {
            margin : 0;
        }

        #MainDiv
        {
            text-align: center;
        }

        #Container
        {
            justify-content : center;
            justify-items : center;
        }

        #Content {
            display: grid;
            grid-template-columns: 0.75fr 0.5fr;
            grid-auto-rows: minmax(100px, auto);
            background-color: #2196F3;
            padding: 10px;
            width: 75%;
            grid-column-gap: 3em;
            justify-content: center;
            margin : auto;

        }

        #Food
        {
            display : grid;
            /*grid-template-columns:repeat(3, 1fr);*/
            grid-template-columns : auto;
        }

        .FoodList {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            grid-auto-columns: minmax(10px, auto);
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            padding-top: 0;
            text-align: center;
        }

        #FoodInfo {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            padding-top: 0;
            text-align: center;
        }
    </style>
</head>
<body>
    <div id="MainDiv">

        <h1>Mindful Body Fitness</h1> <button style="margin-left:1150px" onclick="location.href='@Url.Action("Index", "Fitness")';return false;">Home</button>
        <h2>Food Analysis</h2>

        <div id="Container">

            <div id="Content">

                <div id="Food">

                    <div class="FoodList">
                        <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                        <p>Carbohydrates</p>
                        <p>500g</p>
                    </div>

                    <div class="FoodList">
                        <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                        <p>Proteins</p>
                        <p>90g</p>
                    </div>

                    <div class="FoodList">
                        <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                        <p>Fats</p>
                        <p>100g</p>
                    </div>


                </div> @*end of activities div*@



                <div id="FoodInfo">

                    <p style="display : inline; background-color: #2196F3; width : 100%;">User's Name</p>
                    <p style="display : inline; margin-left : 30px; background-color: #2196F3; width : 100%;">User's Surname</p>

                    <p>In this section, overall information about food intake will be found</p>

                </div> @*Acitibity Info DIV*@

            </div> @*Content Div*@

        </div> @*Container Div*@

    </div> @*main div*@
</body>
</html>

272JABSProject/Views/Fitness/FoodInput.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FoodInput</title>
    <link href="~/Content/brendencss.css" rel="stylesheet" />
</head>
<body>
    <h1 style="text-align:center">Mindfull Body Fitness</h1>
    <h2 style="text-align:center">Food Intake Input</h2>

    <div class="bcontainer">
        <p>
            Food Type: <select id="foodtype" onchange="changeReason()">
                <option value="" selected disabled hidden>Select Type</option>
                <option value="Protein">Protein</option>
                <option value="Carbohydrates">Carbohydrates</option>
                <option value="Fats">Fats</option>
                <option value="Vitamins">Vitamins</option>
                <option value="Water">Water</option>
            </select>
        </p>

        <p>Food Item: <select name="fooditem" id="fooditem">
                <option value="" selected disabled hidden>Select Item</option>
              </select></p>

        <p>Recommended Amount: <input type="text" name="recAmount"></p>

        <p>Actual Amount: <input type="text" name="actAmount"></p>

        <p>
            <button onclick="location.href='@Url.Action("Index", "Fitness")';return false;">Save and Submit</button>
            <button onclick="location.href='@Url.Action("Index", "Fitness")';return false;">Go Home</button>
        </p>

    </div>



    <script>
        function changeReason()
        {
            var selectedStatus = document.getElementById("foodtype");
            var Reason = document.getElementById("fooditem");
            var proteinArray = new Array("Meat", "Chicken", "Egg", "Nuts");
            var carbohydratesArray = new Array("Bread", "Milk", "Potato", "Rice");
            var fatsArray = new Array("Avocado", "Cheese", "Olive oil", "Yogurt");
            var vitaminsArray = new Array("Orange", "Carrot", "Broccoli", "Milk");
            removeOptions(Reason);

            if (selectedStatus.value == "Protein")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = proteinArray[i];
                    option.value = proteinArray[i];
                    Reason.add(option);
                }
            }
            else if (selectedStatus.value == "Carbohydrates")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = carbohydratesArray[i];
                    option.value = carbohydratesArray[i];
                    Reason.add(option);
                }
            }
            else if (selectedStatus.value == "Fats")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = fatsArray[i];
                    option.value = fatsArray[i];
                    Reason.add(option);
                }
            }
            else if (selectedStatus.value == "Vitamins")
            {
                for (var i = 0; i < 4; i++)
                {
                    var option = document.createElement("option");
                    option.text = vitaminsArray[i];
                    option.value = vitaminsArray[i];
                    Reason.add(option);
                }
            }
        }

        function removeOptions(selectbox)
        {
            for (var x = selectbox.options.length - 1; x >= 0; x--)
            {
                selectbox.remove(x);
            }
        }

    </script>

</body>
</html>

272JABSProject/Views/Fitness/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/Styles.css" rel="stylesheet" />
</head>
<body>

    <h1 style="text-align : center;">Mindful Body Fitness</h1>

    <div class="grid-container">


        <div class="grid-item" id="HomePage-Todays-Activities">

            <p style="margin : 0; text-align : left; font-size : 14pt;">Today's Activities</p>

            <div class="grid-grid-container">

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Activity 1</p>
                </div>

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Activity 2</p>
                </div>

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Activity 3</p>
                </div>

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Activity 4</p>
                </div>

            </div>
            @Html.ActionLink("See All", "ActivityAnalysis", "Fitness")
        </div> @*End of todays Activities*@

        <div id="HomePage-Analysis" class="grid-item" style="grid-column-start : 2; grid-column-end : 3 ; grid-row-start : 1 ; grid-row-end : 3">
            <p style="margin : 0; text-align : left; font-size : 14pt;">Analysis</p>
            <hr />

            <div id="HomePage-Activity-Analysis">

                <p style="margin : 0; text-align : left; font-size : 10pt; margin-bottom : 1em;">Activity Analysis</p>

                <div class="HomePage-Analysis-Section">
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                    <p> 1h 31m </p>
                    <p> Running</p>
                </div>

                <div class="HomePage-Analysis-Section">
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                    <p> 1h 31m </p>
                    <p> Running</p>
                </div>

                <div class="HomePage-Analysis-Section">
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                    <p> 1h 31m </p>
                    <p> Running</p>
                </div>

            </div> @*End of Activity Analysis on the home page*@

            <hr />

            <div id="HomePage-Eating-Analysis">

                <p style="margin : 0; text-align : left; font-size : 10pt; margin-bottom : 1em;">Eating Analysis</p>

                <div class="HomePage-Analysis-Section">
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                    <p> Water </p>
                    <p> Amount</p>
                </div>

                <div class="HomePage-Analysis-Section">
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                    <p> Carbohydrates </p>
                    <p> Amount </p>
                </div>

                <div class="HomePage-Analysis-Section">
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="50" width="50">
                    <p> Proteins </p>
                    <p> Amount </p>
                </div>
                @Html.ActionLink("Go To Profile", "UserProfile", "Fitness")
                @Html.ActionLink("LogOut", "LogInPage", "Fitness")
            </div> @*End of Activity Analysis on the home page*@



        </div> @*Analysis section of the Home Page*@

        <div class="grid-item " id="HomePage-Food-Intake">

            <p style="margin : 0; text-align : left; font-size : 14pt;">Today's Food Intake</p>

            <div class="grid-grid-container">

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Food Type 1</p>
                </div>

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Food Type 2</p>
                </div>

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Food Type 3</p>
                </div>

                <div>
                    <img src="http://icons.iconarchive.com/icons/jommans/emluator/128/Pictures-icon.png" alt="picture" height="150" width="150">
                    <p style="margin : 0;">Food Type 4</p>
                </div>

            </div>
            @Html.ActionLink("See All"  , "FoodAnalysis" , "Fitness")
        </div> @*End of Today's food intake*@

        </div>


</body>
</html>

272JABSProject/Views/Fitness/LogInPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LogInPage</title>
    <link href="~/Content/Amo'sStyleSheet.css" rel="stylesheet" />
</head>
<body>
    <h1>Mindful Body Fitness</h1>
    <h1>Log In</h1>

    @using (Html.BeginForm("Login", "Fitness", FormMethod.Post))
    {
        <div class="dvsn">



            <center>
                <label>Email Address:</label> <input type="text" name="EmailAddress" class="center-block" /> <br />

                <label>Password      :</label>      <input type="password" name="Password" class="center-block" /> <br />

                <input type="submit" value="Log In" @*onclick="location.href='@Url.Action("Index","Fitness")'*@"> <input type="submit" value="Create an Account" onclick="location.href='@Url.Action("SignUpPage","Fitness")'">  <br />
                <br />
            </center>
            <br />

        </div>
    }

</body>
</html>

272JABSProject/Views/Fitness/UserProfile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UserProfile</title>
</head>
<body>

    <div style="align-content:center;align-items:center;align-self:center;text-align:center; resize:both;">
        <h1 style="text-align:center">Mindful Body Fitness</h1>
        <br /><br />
        <h2 style="text-align:center">User Profile</h2>
        <br /><br />
        <img style="width:175px; height:189px; align-self:center;" />
        <br />
        <label style="text-align:center;">Name         </label><label style="text-align:center;">Surname          </label>
        <br /><br />
    </div>

    <div style="background-image: linear-gradient(steelblue, #2196F3); width:50%; margin:auto;">
        <label style="background-color:white;">About you:</label>
        <br /><br />


        <label>Nationality  </label><input type="text" style="margin-left:50px;" /> <label style="justify-content:center; margin-left:100px;">Date of Birth    </label><input type="text" style="justify-content:center; margin-left:20px;" />
        <br /><br />
        <label>Gender       </label><input type="text" style="margin-left:75px;"/> <label style="justify-content:center; margin-left:100px;">Country          </label><input type="text" style="justify-content:center; margin-left:50px;" />
        <br /><br />
        <label>Age          </label><input type="number" style="margin-left:95px;"/> <label style="justify-content:center; margin-left:100px">Allergies        </label><input type="text" style="justify-content:center; margin-left:45px;" />
        <br /><br />
        <label>Height       </label><input type="number" style="margin-left:77.5px;"/><label>cm</label> <input type="button" style="margin-left:77.5px;" value="Return to Home",, onclick="location.href='@Url.Action("Index","Fitness")'" />
        <br /><br />
    </div>
</body>
</html>